<?php require 'templates/header.phtml'; ?>

<div class="container my-5">
    <h1 class="text-center">Crear Categoría</h1>
    <form id="form" action="CategoriaCreada" method="POST" class="my-4">
        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre de la Categoría</label>
            <input type="text"  id="nombre" name="nombre" class="form-control" required>
        </div>
        <button type="submit"  value ="Crear Categorias" class="btn btn-primary">Crear Categorias</button>
    </form>
</div>

<?php require 'templates/footer.phtml'; ?>