<?php require 'templates/header.phtml' ?>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form id="form" action="agregado" method="POST" class="my-4">
                <div class="mb-3">
                    <label for="producto" class="form-label">PRODUCTO</label>
                    <input name="producto" type="text" class="form-control" id="producto" required>
                </div>
                <div class="mb-3">
                    <label for="precio" class="form-label">PRECIO</label>
                    <input name="precio" type="number" min="1" class="form-control" id="precio" required>
                </div>
                <div class="mb-3">
                    <label for="categoria" class="form-label">CATEGORÍA</label>
                <select name="categoria" class="form-select" id="categoria" aria-label="Seleccione categoría" required>
                    <option selected>Seleccione categoría</option>
                        <?php foreach ($categorias as $categoria): ?>
                    <option value="<?= $categoria->categoriaID?>"><?= $categoria->nombre?></option>
                        <?php endforeach; ?>
                </select>
                </div>
                <button type="submit" class="btn btn-primary">Guardar</button>
                <?php  if ($id!=null) : ?> 
                    <p>AGREGADO</p>
                <?php endif ?>
            </form>
        </div>
    </div>
</div>

<?php require 'templates/footer.phtml' ?>