<?php require 'templates/header.phtml' ?>

    <form id="form" action="agregado" method="POST" class="my-4">
        <label >PRODUCTO</label>
        <input name="producto" type="text">
        <label>PRECIO</label>
        <input name="precio" type="number" min="1">
        <label>CATEGORIA</label>
        <select name="categoria" class="form-select" aria-label="Default select example">
            <option selected>Seleccione categoria</option>
            <option value="1">electronica</option>
            <option value="2">hogar</option>            
            <option value="3">indumentaria</option>
        </select>
        <input type="submit">
        <?php  if ($id!=null) : ?> 
            <p>AGREGADO</p>
        <?php endif ?>
    </form>

<?php require 'templates/footer.phtml'?> 