<?php require 'templates/header.phtml' ?>

<div class="container my-5">
<?php if (isset($_SESSION['USER_ID'])) : ?>
    <div class="my-3">
        <a href="AgregarCategoria" class="btn btn-primary btn-sm">
            <i class="fas fa-plus"></i> Agregar Categoría
        </a>
    </div>
<?php endif ?>
    <h1 class="text-center">Categorías</h1>
    <div class="row">
        <?php foreach ($categorias as $categoria): ?>
            <div class="col-md-4 mb-4">
                <div class="card h-100 d-flex justify-content-center align-items-center">
                    <div class="card-body text-center">
                        <h5 class="card-title"><?= htmlspecialchars($categoria->nombre) ?></h5>
                        
                        <a href="categoria/<?= $categoria->categoriaID ?>" class="btn btn-success btn-block">Ver Productos</a>
                        
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
</div>
<?php require 'templates/footer.phtml' ?>