<?php require 'templates/header.phtml' ?>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form id="form" action="categoriaEditada/<?= $categoriaID ?>" method="POST" class="my-4">
                <div class="mb-3">
                    <label for="nombre" class="form-label">Nombre de la Categoría</label>
                    <input name="nombre" type="text" class="form-control" id="nombre" required>
                </div>

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<?php require 'templates/footer.phtml' ?>