<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>COMERCIO</title>
</head>
 
<body>
    <header>        
        <div class="dropdown">
        <a href="" type="button" class="btn btn-dark">Home</a>
        <a href="productos" type="button" class="btn btn-dark">Productos</a>
            <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categorias
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
            <?php if (isset($_SESSION['USER_ID'])) : ?>
                <a href="agregar" type="button" class="btn btn-dark">Agregar</a>
            <?php endif ?>
        </div>

        

        <?php if (!isset($_SESSION['USER_ID'])) : ?>
            <a href="login" type="button" class="btn btn-dark float-end" id="boton-login">login</a>
        <?php else : ?>
            <a href="logout" type="button" class="btn btn-dark float-end" id="boton-login">logout(<?= $_SESSION['USER_USER'] ?>)</a>
        <?php endif ?>
    </header>
    
    <main class="container mt-3">