<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>COMERCIO</title>
</head>

<body>
    <a href="" type="button" class="btn btn-dark">Home</a>
    <form method="POST" action="auth">
        <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                <div class="card-body p-5 text-center">

                    <div class="mb-md-5 mt-md-4 pb-5">

                    <h2 class="fw-bold mb-2 text-uppercase">Login</h2>

                    <div class="form-outline form-white mb-4">
                        <input name="user" id="user" class="form-control form-control-lg" />
                        <label class="form-label" for="user">Username</label>
                    </div>

                    <div class="form-outline form-white mb-4">
                        <input name="password" type="password" id="password" class="form-control form-control-lg" />
                        <label class="form-label" for="password">Password</label>
                    </div>

                    <?php if ($error) : ?>
                        <div class='alert alert-danger' role='alert'>
                            <?= $error ?>
                        </div> 
                    <?php endif ?>

                    <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
                    
                </div> 
                </div>
            </div>
            </div>
        </div>
        </section>
    </form>

    <?php require 'templates/footer.phtml' ?>