<?php require 'templates/header.phtml' ?>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="categoria-section">
            <h2>Categoría: <?= htmlspecialchars($categoria->nombre) ?></h2>
                <?php if (isset($_SESSION['USER_ID'])) : ?>
                    <a href="Eliminar/<?= $categoria->categoriaID?>" class="btn btn-danger btn-sm ml-2">Eliminar</a>
                <?php endif ?>
                <a href="EditarCategoria/<?= $categoria->categoriaID ?>" class="btn btn-primary btn-sm">Editar Categoria</a>
        
        </div>
    </div>
</div>

<!-- Mostrar los productos de la categoría -->
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="productos-section">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th>Producto</th>
                            <th>Precio</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($productos as $producto) : ?>
                            <tr>
                                <td><?= htmlspecialchars($producto->producto) ?></td>
                                <td>$<?= $producto->precio?></td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>