<?php require 'templates/header.phtml' ?>

<?php if (isset($_SESSION['USER_ID'])) : ?>
    <div class="my-3">
        <a href="agregar" class="btn btn-primary btn-sm">
            <i class="fas fa-plus"></i> Agregar Producto
        </a>
    </div>
<?php endif ?>

<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#ID</th>
            <th scope="col">Producto</th>
            <th scope="col">Precio</th>
            <th scope="col">Categoría</th>
            <?php if (isset($_SESSION['USER_ID'])) : ?>
                <th scope="col">Acciones</th>
            <?php endif ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($productos as $producto): ?>
            <tr>
                <th scope="row"><?= $producto->id ?></th>
                <td><a href="producto/<?= $producto->id ?>"><?= $producto->producto ?></td>
                <td><?= $producto->precio ?></td>
                <td><?=$producto->Nombre?></a></td>
                <?php if (isset($_SESSION['USER_ID'])) : ?>
                    <td>
                        <a href="editar/<?= $producto->id ?>" class="btn btn-primary btn-sm">Editar</a>
                        <a href="eliminar/<?= $producto->id ?>" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                <?php endif ?>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
<p class="mt-3"><small>Total: <?=$count?> productos</small></p>
<?php require 'templates/footer.phtml'?> 