<?php require 'templates/header.phtml' ?>

<table class='table table-hover'>
    <thead>
        <tr>
            <th>#ID</th>
            <th>Producto</th>
            <th>Precio</th>
            <th>Categoria</th>
        </tr>
    </thead>
    <tbody>    
    <?php foreach($productos as $producto):?>
        <tr>
            <td><?=$producto->id?></td>
            <td><?=$producto->producto?></td>
            <td><?=$producto->precio?></td>
            <td><?=$producto->Nombre?></td>
            
            <?php if (isset($_SESSION['USER_ID'])) : ?>
            <td>
                <a href="editar/<?=$producto->id?>" type="button" class="btn btn-dark">Editar</a>
                <a href="eliminar/<?=$producto->id?>" type="button" class="btn btn-dark">Eliminar</a>
            </td>
            <?php endif ?>

        </tr>        
    <?php endforeach ?>
    </tbody>
</table>
<p class="mt-3"><small>total: <?=$count?> productos</small></p>
<?php require 'templates/footer.phtml'?> 